### ISSUE TITLE
Enable HLM to create multiple columns for the vegetated landunit 

### ISSUE THREAD

**Issue by glemieux** [NGEET/E3SM#2]
The current model assumes a single column for the vegetated landunit, which is added upon gridcell initliazation:
https://github.com/NGEET/E3SM/blob/67abd002e90036f0c0d7baeb10b8a55a2965e7a7/components/elm/src/main/initGridCellsMod.F90#L347-L348

We will need to allow multiple soil columns for a vegetated land unit to be added during initialization such that when we have disturbance of the soil we move the appropriate patches and their area to the appropriate time-since-fire age class bin column.  This movement  will need to be triggered by a disturbance mechanism similar to what we do with fates.   

This will require updating the column weighting for the relevant upstream hierarchical unit: https://github.com/NGEET/E3SM/blob/67abd002e90036f0c0d7baeb10b8a55a2965e7a7/components/elm/src/data_types/ColumnType.F90#L34-L40 

```[tasklist]
### Tasks
- [ ] https://github.com/NGEET/E3SM/issues/3
- [ ] https://github.com/NGEET/E3SM/issues/4
- [ ] https://github.com/NGEET/E3SM/issues/6
- [ ] https://github.com/NGEET/E3SM/issues/7
- [ ] https://github.com/NGEET/E3SM/issues/12
```

**Comment by glemieux** [comment]
Not that currently all calls to `add_column` take place in `initGridCellsMod` via different `set_landunit_...` calls.  These are all wrapped up in the `initGridCells` subroutine.
